// Generated by scripts/optimize-images.mjs. Do not edit by hand.

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL?: string;
};

export const siteImages = {
  blueprintReview: {
    src: "/images/blueprint-review",
    width: 2400,
    height: 1350,
    blurDataURL: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQAAkAA4BaJZQC7AYtVdXdii4PKwAA/vG5qIT4rH3/a0lHn/gLeDoRt1xBllVL9ZcIVrMhEw2b6iQrvhmq3QKUjJY9BfLMju7Mfn4nTV0+p5PGpfT7jQOAAAA=",
  },
  canadaProperty: {
    src: "/images/canada-property",
    width: 1800,
    height: 1200,
    blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAQCdASoQAAsAA4BaJYgCdABzdEQwAP5BJUS1NMMVcrnIzJ1Cct6KcTIdz5lUki9liSfCXUm8O6bCc7vCwHjHrNGHgzkr0I5OqyAoPMdrnfcnaPGrpuLjr8lg4rwA",
  },
  conferenceRoom: {
    src: "/images/conference-room",
    width: 2400,
    height: 1602,
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAsAA4BaJZwCsACVEfI/AAD+Ttuhi9EL170ik8FE++T0EetQS3qCS71gyZO4qPoiSEQbPaa++CpNC/x99BU0EuKXaqZZ1yLWPUxeDPAAAA==",
  },
  ctaDocumentReview: {
    src: "/images/cta-document-review",
    width: 1800,
    height: 1201,
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAsAA4BaJYwAAv9XevEOtRPAAP4Y8E6m+a+P6WzPO3SEmLMr0ImTcWj5GLe1l/R+ViwSPEakzYERs+/zf/b2dB0II/XfNLbliRylAiQ0yBBwlKtrycEIKyAAAA==",
  },
  heroOfficeTowers: {
    src: "/images/hero-office-towers",
    width: 2400,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQAAsAA4BaJQBOgMWg1RTtYtI7HgAA/phVqDaPo9OXao6U98AjtHIid/hkbYd6E0d9fYwvKhMg2JD6mH/sJZhiL0rMML5Ib9TLZnF3T4xzpPvQjEORMAAA",
  },
  officeInterior: {
    src: "/images/office-interior",
    width: 2400,
    height: 1602,
    blurDataURL: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAsAA4BaJZQC7AELR5AAAP40cINYvSMnya0CVd7am4uMmgIAK0wMumII68mnQ0zzRYOJspYHv7TI9YAAAA==",
  },
  saudKhan: {
    src: "/images/saud-khan",
    width: 1099,
    height: 1374,
    blurDataURL: "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCdABulCQ0Y/uXzVM6iAAD+0Vvgyb8GOOrMw3/oYmJXz2dbjgC80cax+j3lb/0KhylD7hvk/u4em50fik7Smp0ytZtZ415M7RGXB6Cjsf2PCcf8YUmL3F+DvptXgHXz+1bsnnyEXBkHIyIroAB7DTgxgjsUQAA=",
  },
  torontoSkyline: {
    src: "/images/toronto-skyline",
    width: 2400,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQAAsAA4BaJZQC7ACRtboAAP2thsT8fEx/JKXTnUzjA5Iu0OXBGdsIx6kBSo8KPaOBSFvTRp5sYPi/AAA=",
  },
  logoHorizontalOnDark: {
    src: "/images/logo-horizontal-on-dark",
    width: 1040,
    height: 238,
  },
} satisfies Record<string, SiteImage>;
