/**
 * Build-time image optimization.
 *
 * Reads source images from src/assets/images and src/assets/brand, writes a WebP
 * file for every width next/image may request into public/images, and writes a
 * typed manifest (dimensions + blur placeholder) to src/content/images.generated.ts.
 *
 * Images are optimized once at build time, so the Worker never transforms images at
 * runtime. Runs automatically before `dev` and `build`.
 */
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceDirs = ["src/assets/images", "src/assets/brand"];
const outputDir = path.join(root, "public/images");
const manifestFile = path.join(root, "src/content/images.generated.ts");

const { deviceSizes, imageSizes } = JSON.parse(
  await readFile(path.join(root, "src/config/image-widths.json"), "utf8"),
);
const widths = [...imageSizes, ...deviceSizes].sort((a, b) => a - b);

const toKey = (name) => name.replace(/[-_ ]+([a-z0-9])/gi, (_, char) => char.toUpperCase());

await rm(outputDir, { recursive: true, force: true });
await mkdir(outputDir, { recursive: true });

const entries = [];

for (const dir of sourceDirs) {
  const files = (await readdir(path.join(root, dir))).filter((file) =>
    /\.(jpe?g|png)$/i.test(file),
  );

  for (const file of files.sort()) {
    const source = path.join(root, dir, file);
    const name = path.parse(file).name;
    const { width, height, hasAlpha } = await sharp(source).metadata();

    await Promise.all(
      widths.map(async (target) => {
        await sharp(source)
          .resize({ width: target, withoutEnlargement: true })
          .webp({ quality: hasAlpha ? 90 : 76, alphaQuality: 100, effort: 5 })
          .toFile(path.join(outputDir, `${name}-${target}.webp`));
      }),
    );

    const blur = hasAlpha
      ? undefined
      : `data:image/webp;base64,${(
          await sharp(source).resize({ width: 16 }).webp({ quality: 40 }).toBuffer()
        ).toString("base64")}`;

    entries.push({ key: toKey(name), src: `/images/${name}`, width, height, blur });
  }
}

const body = entries
  .map(({ key, src, width, height, blur }) => {
    const blurLine = blur ? `\n    blurDataURL: "${blur}",` : "";
    return `  ${key}: {\n    src: "${src}",\n    width: ${width},\n    height: ${height},${blurLine}\n  },`;
  })
  .join("\n");

await writeFile(
  manifestFile,
  `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\n\nexport type SiteImage = {\n  src: string;\n  width: number;\n  height: number;\n  blurDataURL?: string;\n};\n\nexport const siteImages = {\n${body}\n} satisfies Record<string, SiteImage>;\n`,
);

console.log(`Optimized ${entries.length} images into ${widths.length} widths each.`);
